start-chat:
    uv run python src/main.py

check:
    uv run ruff check src
    uv run ruff format src --check
    uv run ty check src

fix:
    uv run ruff check src --fix
    uv run ruff format src
    uv run ty check src
